version: 2.1
commands:
  runtests:
    description: "Install deps and run tests"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --build-from-source
      - run:
          name: Run Tests
          command: npm test
          when: always

workflows:
  main:
    jobs:
      - unit-tests-node8
      - unit-tests-node10
      - unit-tests-node12

jobs:
  unit-tests-node8:
    docker:
      - image: circleci/node:8
    steps:
      - runtests
  unit-tests-node10:
    docker:
      - image: circleci/node:10
    steps:
      - runtests
  unit-tests-node12:
    docker:
      - image: circleci/node:12
    steps:
      - runtests
